name: Check PHP Coding Standards with PHP-CS-Fixer

on:
  workflow_call:
    inputs:
      php:
        description: PHP Version to use
        default: 7.4
        required: false
        type: string
      version:
        description: php-cs-fixer version to use
        default: '*'
        required: false
        type: string

jobs:
  cs-check:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          coverage: none
          tools: php-cs-fixer:${{ inputs.version }}

      - name: Check CS
        run: php-cs-fixer fix --dry-run --diff
