name: Run php-cs-fixer and commit any fixes

on:
  workflow_call:
    inputs:
      php:
        description: PHP Version to use
        required: true
        type: string
      version:
        description: php-cs-fixer version to use
        default: '3'
        required: false
        type: string

jobs:
  fixcs:
    name: Fix CS
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          coverage: none
          tools: php-cs-fixer:${{ inputs.version }}

      - name: Check CS
        run: php-cs-fixer fix --verbose --diff

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ inputs.key }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit files fixed with php-cs-fixer
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          branch: "${{ github.head_ref }}"
          commit_options: '-S'
          commit_message: "bot: fix cs [skip ci]"
          commit_user_email: "kevinbond@gmail.com"
          commit_user_name: "Kevin Bond (bot)"
